import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { DM_Sans } from "next/font/google";
import { ThemeProvider } from "@/contexts/theme";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyTypeface = DM_Sans({
  weight: "variable",
  subsets: ["latin", "latin-ext"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={cn("antialiased dark:text-white", bodyTypeface.className)}
        >
          <div className="sticky top-0 z-10 w-full border-b bg-white">
            <Header className="max-container" />
          </div>

          <div className="max-container my-4">{children}</div>

          <div className="w-full bg-slate-900 text-white">
            <footer className="max-container w-full py-4">Footer</footer>
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
